import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { type PropsWithChildren } from 'react';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-slate-900`}
      >
        <div className="my-2 xl:mx-48 lg:mx-36 md:mx-12 sm:mx-6 mx-4">
          {props.children}
        </div>
      </body>
    </html>
  );
}
